services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - es
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/cooking_book"
      NEXTAUTH_SECRET: "your_secret"
      GOOGLE_CLIENT_ID: "your_google_client_id"
      GOOGLE_CLIENT_SECRET: "your_google_client_secret"
      FACEBOOK_CLIENT_ID: "your_facebook_client_id"
      FACEBOOK_CLIENT_SECRET: "your_facebook_client_secret"
    volumes:
      - .:/app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cooking_book
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_PASSWORD=elastic_password
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  es_data:
